# Generated by Django 6.0.2 on 2026-03-27 04:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Performance Record', 'verbose_name_plural': 'Performance Records'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Attendance percentage for the month', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Attendance %'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='calculated_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated performance score', max_digits=5, null=True, verbose_name='Calculated Score'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='goals_completed',
            field=models.IntegerField(help_text='Number of goals achieved this month', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goals Completed'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='Rate the employee from 1 (poor) to 10 (excellent)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Rating (1-10)'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['calculated_score'], name='performance_calcula_0941b4_idx'),
        ),
    ]
