# Generated by Django 6.0.2 on 2026-03-27 04:56

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['employee_id']},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_employe_0cbd94_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_role_1fa9a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_employm_fa337b_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_is_soft_a162c7_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True, validators=[accounts.models.validate_joining_date]),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter valid phone number')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('HR', 'Human Resources'), ('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
    ]
